// lazy-loading-vue/src/views/Home.vue
<template>
  <div>
    <p>I am the <strong>home</strong> component.</p>
    <button v-on:click="showMe">{{ showFibonacci ? 'Hide' : 'Show' }}</button>

    <div v-if="showFibonacci">
      <Fibonacci />
    </div>
  </div>
</template>

<script>
import Fibonacci from './Fibonacci.vue';
export default {
  name: 'Home',
  data: () => ({
    showFibonacci: false
  }),
  methods: {
    showMe: function() {
      this.showFibonacci = !this.showFibonacci;
    }
  },
  components: {
    Fibonacci
    // Fibonacci: () => import('./Fibonacci.vue')
  }
};
</script>

// lazy-loading-react/src/components/Home.js
import React, { Suspense, useState, lazy } from 'react';
// import Fibonacci from './Fibonacci';
const Fibonacci = lazy(() => import('./Fibonacci'));

const Home = () => {
  const [showFibonacci, setShowFibonacci] = useState(false)
  const showMe = () => setShowFibonacci(!showFibonacci);
  return (
  <>
    <p>I am the <strong>home</strong> component.</p>
    <button onClick={showMe}>{ showFibonacci ? 'Hide' : 'Show' }</button>
    
    {/* { showFibonacci ? <Fibonacci /> : '' } */}
    { showFibonacci ? <Suspense fallback={<div>Loading...</div>}> <Fibonacci /></Suspense> : '' }
  </>
)};

export default Home;
