// lazy-loading-react/src/components/Fibonacci.js
import React from 'react';

const fibonacci = num => {
  if (num <= 1) return 1;
  return fibonacci(num - 1) + fibonacci(num - 2);
};

const fib = fibonacci(42);

const Fibonacci = () => (
  <>
    <p>Hello, this is the <strong>Fibonacci</strong> component. For fun I calculated the 42nd Fibonacci number which is: { fib }.</p>
  </>
);

export default Fibonacci;

// lazy-loading-angular/src/app/fibonacci/fibonacci.component.ts
import { Component, OnInit } from '@angular/core';

const fibonacci = num => {
  if (num <= 1) return 1;
  return fibonacci(num - 1) + fibonacci(num - 2);
};
console.log(fibonacci(42));

@Component({
  selector: 'app-fibonacci',
  templateUrl: './fibonacci.component.html',
  styleUrls: ['./fibonacci.component.css']
})
export class FibonacciComponent implements OnInit {

  constructor() { }
  
  fibonacci: number;

  ngOnInit(): void {
    const fibonacci = num => {
      if (num <= 1) return 1;
      return fibonacci(num - 1) + fibonacci(num - 2);
    };
    this.fibonacci = fibonacci(42);
  }

}
<p>
  Hello, this is the <strong>Fibonacci</strong> component. For fun I
  calculated the 42nd Fibonacci number which is: {{ fibonacci }}.
</p>
